# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

from fire import db
from PyQt5 import QtCore, QtGui, QtWidgets
from request import Ui_RequestWindow
from assign import Ui_AssignWindow
from employee import Ui_EmployeeWindow


class Ui_WelcomeWindow(object):
    def __init__(self,message1):
        self.email=message1
        users_by_email = db.child("users").order_by_child("email").equal_to(self.email).get()
        a=users_by_email.val()
        for key in a.keys():
            x=a[key]
            self.eidf=key
        self.namef=x['name']
        self.mngridf=x['mngr_ssn']
        self.plr=x['pen_req_made']
        self.pla=x['pen_req_rec']
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(951, 664)
        MainWindow.setMinimumSize(QtCore.QSize(951, 664))
        MainWindow.setMaximumSize(QtCore.QSize(951, 664))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(-60, -60, 1091, 711))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("background3.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.background.raise_()
        self.s_d = QtWidgets.QPushButton(self.centralwidget)
        self.s_d.setGeometry(QtCore.QRect(260, 370, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.s_d.setFont(font)
        self.s_d.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s_d.setObjectName("s_d")
        self.r_l = QtWidgets.QPushButton(self.centralwidget)
        self.r_l.setGeometry(QtCore.QRect(440, 370, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.r_l.setFont(font)
        self.r_l.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.r_l.setObjectName("r_l")
        self.a_l = QtWidgets.QPushButton(self.centralwidget)
        self.a_l.setGeometry(QtCore.QRect(620, 370, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.a_l.setFont(font)
        self.a_l.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.a_l.setObjectName("a_l")
        self.welcome = QtWidgets.QLabel(self.centralwidget)
        self.welcome.setGeometry(QtCore.QRect(330, 0, 481, 81))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.welcome.setFont(font)
        self.welcome.setObjectName("welcome")
        self.name_lb = QtWidgets.QLabel(self.centralwidget)
        self.name_lb.setGeometry(QtCore.QRect(280, 160, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.name_lb.setFont(font)
        self.name_lb.setObjectName("name_lb")
        self.empid_lb = QtWidgets.QLabel(self.centralwidget)
        self.empid_lb.setGeometry(QtCore.QRect(280, 130, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.empid_lb.setFont(font)
        self.empid_lb.setObjectName("empid_lb")
        self.eid_lb = QtWidgets.QLabel(self.centralwidget)
        self.eid_lb.setGeometry(QtCore.QRect(280, 190, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.eid_lb.setFont(font)
        self.eid_lb.setObjectName("eid_lb")
        self.select_option_lb = QtWidgets.QLabel(self.centralwidget)
        self.select_option_lb.setGeometry(QtCore.QRect(410, 310, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.select_option_lb.setFont(font)
        self.select_option_lb.setObjectName("select_option_lb")
        self.mngrid_lb = QtWidgets.QLabel(self.centralwidget)
        self.mngrid_lb.setGeometry(QtCore.QRect(280, 220, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.mngrid_lb.setFont(font)
        self.mngrid_lb.setObjectName("mngrid_lb")
        self.pla_lb = QtWidgets.QLabel(self.centralwidget)
        self.pla_lb.setGeometry(QtCore.QRect(200, 510, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.pla_lb.setFont(font)
        self.pla_lb.setObjectName("pla_lb")
        self.plr_lb = QtWidgets.QLabel(self.centralwidget)
        self.plr_lb.setGeometry(QtCore.QRect(200, 540, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.plr_lb.setFont(font)
        self.plr_lb.setObjectName("plr_lb")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(160, 290, 691, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.penas_count = QtWidgets.QLabel(self.centralwidget)
        self.penas_count.setGeometry(QtCore.QRect(440, 510, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.penas_count.setFont(font)
        self.penas_count.setObjectName("penas_count")
        self.penrq_count = QtWidgets.QLabel(self.centralwidget)
        self.penrq_count.setGeometry(QtCore.QRect(440, 540, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.penrq_count.setFont(font)
        self.penrq_count.setObjectName("penrq_count")
        self.empid = QtWidgets.QLabel(self.centralwidget)
        self.empid.setGeometry(QtCore.QRect(410, 130, 471, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(8)
        self.empid.setFont(font)
        self.empid.setObjectName("empid")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(410, 160, 511, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(8)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.eid = QtWidgets.QLabel(self.centralwidget)
        self.eid.setGeometry(QtCore.QRect(410, 190, 521, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(8)
        self.eid.setFont(font)
        self.eid.setObjectName("eid")
        self.mngrid = QtWidgets.QLabel(self.centralwidget)
        self.mngrid.setGeometry(QtCore.QRect(410, 220, 501, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(8)
        self.mngrid.setFont(font)
        self.mngrid.setObjectName("mngrid")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 951, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.refreshd = QtWidgets.QPushButton(self.centralwidget)
        self.refreshd.setGeometry(QtCore.QRect(490, 510, 70, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.refreshd.setFont(font)
        self.refreshd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refreshd.setObjectName("refreshd")
        self.refreshd.setText("Refresh")

        self.r_l.clicked.connect(self.Open_RequestWindow)
        self.a_l.clicked.connect(self.Open_AssignWindow)
        self.s_d.clicked.connect(self.Open_EmployeeWindow)
        self.refreshd.clicked.connect(self.clickedrefreshd)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.s_d.setText(_translate("MainWindow", "Subordinates details"))
        self.r_l.setText(_translate("MainWindow", "Request Leaves"))
        self.a_l.setText(_translate("MainWindow", "Assigned Leaves"))
        self.welcome.setText(_translate("MainWindow", "Welcome User"))
        self.name_lb.setText(_translate("MainWindow", "NAME: "))
        self.empid_lb.setText(_translate("MainWindow", "EMPLOYEE ID:"))
        self.eid_lb.setText(_translate("MainWindow", "EMAIL ID:"))
        self.select_option_lb.setText(_translate("MainWindow", "Select an Option"))
        self.mngrid_lb.setText(_translate("MainWindow", "MANAGER ID:"))
        self.pla_lb.setText(_translate("MainWindow", "PENDING LEAVES ASSIGNED: "))
        self.plr_lb.setText(_translate("MainWindow", "PENDING LEAVES REQUESTED:"))
        self.penas_count.setText(_translate("MainWindow", str(self.pla)))
        self.penrq_count.setText(_translate("MainWindow", str(self.plr)))
        self.empid.setText(_translate("MainWindow", self.eidf))
        self.name.setText(_translate("MainWindow", self.namef))
        self.eid.setText(_translate("MainWindow", self.email))
        self.mngrid.setText(_translate("MainWindow", self.mngridf))
    
    def Open_RequestWindow(self):
        self.RequestWindow = QtWidgets.QMainWindow()
        self.ui = Ui_RequestWindow(self.eidf,self.mngridf)
        self.ui.setupUi(self.RequestWindow)
        self.RequestWindow.show()
    def Open_AssignWindow(self):
        self.AssignWindow = QtWidgets.QMainWindow()
        self.ui = Ui_AssignWindow(self.eidf)
        self.ui.setupUi(self.AssignWindow)
        self.AssignWindow.show()
    def Open_EmployeeWindow(self):
        self.EmployeeWindow = QtWidgets.QMainWindow()
        self.ui = Ui_EmployeeWindow(self.eidf)
        self.ui.setupUi(self.EmployeeWindow)
        self.EmployeeWindow.show()
    def clickedrefreshd(self):
        self.plr=db.child("users").child(self.eidf).child("pen_req_made").get().val()
        self.pla=db.child("users").child(self.eidf).child("pen_req_rec").get().val()
        self.penrq_count.setText(str(self.plr))
        self.penas_count.setText(str(self.pla))